# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  job1:
    install-and-test:
      runs-on: ubuntu-latest

      strategy:
        matrix:
          node-version: [17.x]

      steps:
        - uses: actions/checkout@master

        - name: Set up Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@master
          with:
            node-version: ${{ matrix.node-version }}

        - name: Install packages
          run: yarn install --frozen-lockfile
  job2:
    needs: job1
      steps:

        - name: Test
          run: yarn test
          
        # - name: Set up Docker Buildx
        #   uses: docker/setup-buildx-action@v2
        
        # - name: Login to DockerHub
        #   uses: docker/login-action@v2
        #   with:
        #     username: ${{ secrets.DOCKERHUB_USERNAME }}
        #     password: ${{ secrets.DOCKERHUB_TOKEN }}

        # - name: Build and push
        #   uses: docker/build-push-action@v3
        #   with:
        #     push: true
        #     tags: boriwat01/numer_client_cd:latest

  job3:
    needs: [job1,job2]
        steps:
        - uses: actions/checkout@v2
        - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
          with:
            heroku_api_key: ${{secrets.HEROKU_API_KEY}}
            heroku_app_name: "numerclient" #Must be unique in Heroku
            heroku_email: "boriwat1211@gmail.com"
